<form class="form password validate"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/validatepost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your magento password to link your account.'); ?></div>
        <div class="field email required">
            <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
            <div class="control">
                <input type="password" name="password" alt="password" id="password" class="input-text" value="" data-validate="{required:true}">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ /* echo $block->getLoginUrl() */ ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
