<div class="amazon-button-container">
    <div class="amazon-button-container__cell">
        <div id="LoginWithAmazon" class="login-with-amazon" data-mage-init='{"amazonButton": {"buttonType": "LwA", "redirectURL" : "<?php echo $block->getUrl('amazon/login/authorise', ['_secure' => true]) ?>"}}'></div>
    </div>
    <div class="amazon-button-container__cell">
        <div class="field-tooltip toggle">
            <span class="field-tooltip-action action-help" data-mage-init='{"dropdown": {"activeClass": "_active"}}' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
            <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true">Are you an Amazon customer?</div>
        </div>
    </div>
</div>
