<?php
$helper = $this->helper('Amazon\Login\Helper\Data');
?>
<?php if ($helper->getLoginEnabled()): ?>
    <?php
    $buttonData = [
        'amazonButton' => [
            'buttonType' => $helper->getButtonType(),
            'buttonColor' => $helper->getButtonColor(),
            'buttonSize' => $helper->getButtonSize(),
            'redirectURL' => $block->getUrl('amazon/login/authorise', ['_secure' => true])
        ]
    ];
    ?>
<div class="amazon-button-container">
    <div class="amazon-button-container__cell">
        <div id="LoginWithAmazon" class="login-with-amazon" data-mage-init='<?php echo json_encode($buttonData); ?>'></div>
    </div>
    <div class="amazon-button-container__cell">
        <div class="field-tooltip toggle">
            <span class="field-tooltip-action action-help" data-mage-init='{"dropdown": {"activeClass": "_active"}}' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
            <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true">Are you an Amazon customer?</div>
        </div>
    </div>
</div>
<?php endif; ?>
