magento_existing_amazon_login_token_info:
  request:
    path: "/auth/o2/tokeninfo"
    methods: ['GET']
    query:
      access_token: "Atza|IpFFMdZjI2qp1UQ3dXqX3uTsHJrNvxzENQI1SSNfKyLU6LQR2S3YOjAADBHYFBqqAy07FLD2IL6OAbD0YwUnnsbCN1gzubYfsyEudkyqvXFJREMNTijuhMUbjjl5Mnot2O42KsQnsGyNd_w7QDI4CYByg-2amX1Q6RBpgdGYRMzsGTOVCkT-vCWVNnSB5risO9ck0D9lBFfzG160WFfwlih8sSqsJr_RmEWyMad0bOBwPqU3kvu45X6OSjTCnbuD4firhr2aDXC3s2YJT0Bd1CMvb5GKBKQkH70BIAnNiAvSDjQUJM4Lb5RO9tVPqkZ2-akbzop5zFDXsv5hqiqefAIB0ZN5AuZDP6f-Tc0bR_AiQdzq-5Yyoj1qN26_qtXeMZMsjaYcZ9H15H7qH7Y6-0HXU0xbk3Z1sLH73odg3aqqNlmj5drLxcNXq14gLdw7eyse5gfEmZaIomo1VL9IR7J1tN1Z67SELr1vbiB4TeRpYJ-ie0PLRObsKo-tDfRZ6dV7u1MfigCUFZ0fdPq4t6y2WGQoRPq1zpCx3iiEGhTat78LQ79ecJLT0E1LiG0Zj9R3bnlSrHVVv43OrixNhjicV6CcCQ4zq-kIF31BPyTCoQXM"
  response:
    content: |
      {% include '@resources/tokeninfo.json.twig' with {aud: "amzn1.application-oa2-client.15d69a1a3b83453a81ab480224d811cd", userId: "amzn1.account.VQ3AF2JFB5H7K5JZRDIZHUH7IVNH", appId: "amzn1.application.eec3fff693344f049d76b4bbbc690dc0"} %}

magento_existing_amazon_login_user_profile:
  request:
    path: "/user/profile"
    methods: ['GET']
    headers:
      Authorization: "bearer Atza|IpFFMdZjI2qp1UQ3dXqX3uTsHJrNvxzENQI1SSNfKyLU6LQR2S3YOjAADBHYFBqqAy07FLD2IL6OAbD0YwUnnsbCN1gzubYfsyEudkyqvXFJREMNTijuhMUbjjl5Mnot2O42KsQnsGyNd_w7QDI4CYByg-2amX1Q6RBpgdGYRMzsGTOVCkT-vCWVNnSB5risO9ck0D9lBFfzG160WFfwlih8sSqsJr_RmEWyMad0bOBwPqU3kvu45X6OSjTCnbuD4firhr2aDXC3s2YJT0Bd1CMvb5GKBKQkH70BIAnNiAvSDjQUJM4Lb5RO9tVPqkZ2-akbzop5zFDXsv5hqiqefAIB0ZN5AuZDP6f-Tc0bR_AiQdzq-5Yyoj1qN26_qtXeMZMsjaYcZ9H15H7qH7Y6-0HXU0xbk3Z1sLH73odg3aqqNlmj5drLxcNXq14gLdw7eyse5gfEmZaIomo1VL9IR7J1tN1Z67SELr1vbiB4TeRpYJ-ie0PLRObsKo-tDfRZ6dV7u1MfigCUFZ0fdPq4t6y2WGQoRPq1zpCx3iiEGhTat78LQ79ecJLT0E1LiG0Zj9R3bnlSrHVVv43OrixNhjicV6CcCQ4zq-kIF31BPyTCoQXM"
  response:
    content: |
      {% include '@resources/profile.json.twig' with {userId: "amzn1.account.VQ3AF2JFB5H7K5JZRDIZHUH7IVNH", name: "John Doe", email: "existingamazon@example.com"} %}